print("--------------------")
print("Magi Educational Equipment Store")
print("--------------------")
print("Pen       x 1  :  10 THB")
print("Eraser    x 1  :   5 THB")
print("Pencil    x 1  :   7 THB")
print("A ruler   x 1  :  15 THB")
print("Sharpener x 1  :  10 THB")
print("Notebook  x 1  :  20 THB")
print("Crayon    x 1  :  50 THB")
print("Liquid    x 1  :  20 THB")
print("--------------------")
print("Total 8 pieces : 137 THB")
print("-----Thank you------")